### PR TITLE
Use .NET Core 2 to build and run the Koans

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Hello.

I want to help you out a bit with the .NET Core transition and with those tickets:
* https://github.com/ChrisMarinos/FSharpKoans/issues/55
* https://github.com/ChrisMarinos/FSharpKoans/issues/59

I've seen the PR 
https://github.com/ChrisMarinos/FSharpKoans/pull/60/
but it changes quite a lot of files, so I've decided to make another one, smaller but already making it way more easy to use the project.

I'm new to .NET world, so there is a high probability that I might have missed something in the configuration files, but I've checked the PR and it works fine in latest Linux Mint and macOS.

### CODE REVIEW

**Comment by baronfel** [comment]
Yeah, this builds and runs fine for me too.  The only thing I might add is using `dotnet watch` as a CLI tool so that a user can run `dotnet watch run -p FSharpKoans/FSharpKoans.fsproj` and have the tests auto-run as they make code changes. (Some examples)[https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/dotnet-watch.md#add-dotnet-watch-to-a-project]

**Comment by SomeoneToIgnore** [comment]
Nice idea, have added.

One thing to note: `dotnet watch run -p FSharpKoans/FSharpKoans.fsproj` does not work for me, but if you run `dotnet watch run` from the `FSharpKoans` directory, it works.

**Comment by baronfel** [comment]
ping! How are we feeling about this PR? I think it's in a pretty good state and makes the initial onboarding experience pretty great, especially with `dotnet watch`!

**Comment by ChrisMarinos** [comment]
Gah! Sorry for missing this. I was able to pull everything down and run it successfully. I think this looks really good, and I really appreciate the contribution. I'll go ahead and merge this now.

**Pull request merged**
