### PR TITLE
WIP: .Net Core Support!

### PR DESCRIPTION
**Pull request by baronfel**
This PR abandons Mono/.Net Framework in favor of .Net Core.

Everything's all set up now to where all a user has to do is:
```
dotnet restore
dotnet build
dotnet run

and/or 
dotnet watch run
```

on any platform to get the tests to run.

This PR is on top of the expecto changes in my other PR, so I've marked is as WIP.

### CODE REVIEW

**Comment by baronfel** [comment]
@vilinski you had some curiosity about it, well here it is :D

**Comment by ChrisMarinos** [comment]
Hurray for dotnet core support! I was actually just working on a local branch to support this for one of my coworkers, but I'm glad you have it working. I played with this branch locally, and everything seems to work well on my OSX machine. My only concern with this branch is that it raises the barrier to entry for VS users. While I _love_ that this makes it easier for VS Code and other non-studio users to access the koans, I'm hesitant to make things more difficult for the VS crowd. What are your thoughts on preserving out-of-the-box support for VS, perhaps using a separate FSharpKoans-VisualStudio.fsproj that we call out in the README?

**Comment by baronfel** [comment]
That'd be doable too!  I can drop that back in there too.

Hopefully the day that we can drop that for our VS friends comes soon :)

**Comment by ChrisMarinos** [comment]
Totally agree- it would be nice if we could have one format to rule them all! If this project wasn't designed to be a welcoming introduction to the language, I'd just force everyone to use .Net Core and be done with it. :-)

**Pull request closed without merging**
