### PR TITLE
Add a Docker runner

### PR DESCRIPTION
**Pull request by craigjbass**

### CODE REVIEW

**Comment by normanhh3** [comment]
Looks like a cool PR!  My only question after reviewing is, do you still update the .fs files on the host system, and then the docker container - because of the `dotnet watch` monitors for the changes?

**Comment by ChrisMarinos** [comment]
FYI, I’m on vacation at the moment, but I’ll check this out when I return. Looks like a good idea!

**Comment by craigjbass** [comment]
The docker command mounts the local file system - so watch will pick up any changes.

**Comment by ChrisMarinos** [comment]
I took this branch out for a spin, and it's absolutely great. It makes it dead-simple to get up and running. Thanks for the great addition!

**Pull request merged**
